kubeconfig: /config/kubeconfig

api:
  port: 8080

rest:
  enabled: true

metrics:
  enabled: true

ui:
  enabled: true

target:
  loki:
    host: http://host.docker.internal:31000
    path: /loki/api/v1/push
    minimumPriority: ""
    skipExistingOnStartup: false

database:
  type: sqlite
  database: /data/policy-reporter.db

reportFilter:
  namespaces:
    include: []
  clusterReports:
    disabled: false
